### ISSUE TITLE
I want you to add the card of your information and an image 

### ISSUE THREAD

**Issue by TrustAFK** [TrustAFK/Student_Info#8]

**Comment by iAdityaSharma2912** [comment]
I want to participate in this.

**Comment by Tushar-gupta-git** [comment]
ok krlo bhai

**Comment by Ankur-Sh** [comment]
i wanna participate

**Comment by Tushar-gupta-git** [comment]
> i wanna participate

Sure

**Comment by AK-codingmaniac** [comment]
Hey @Tushar-gupta-git I have added my card
Please merge it as soon as possible if there were no errors

**Comment by Aishaa-26** [comment]
I want to contribute, please assign it to me.

**Comment by Tushar-gupta-git** [comment]
Complete the task and make a pull request. I'll assign you :)

**Comment by amitkroutthedev** [comment]
I want to contribute, please assign it to me.

**Comment by VladenCode** [comment]
I would like to commit to this project. :)

**Comment by jayantchaudhari18** [comment]
Hey @Tushar-gupta-git  I would like to work on this issue.

**Comment by Omm2005** [comment]
Hey I wanna contribute in this!

**Comment by Tushar-gupta-git** [comment]
> Hey @Tushar-gupta-git I would like to work on this issue.

sure go for it
